{% set name = "djvulibre" %}
{% set version = "3.5.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/djvu/DjVuLibre/{{ version }}/djvulibre-{{ version }}.tar.gz
  sha256: d3b4b03ae2bdca8516a36ef6eb27b777f0528c9eda26745d9962824a3fdfeccf

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - pkg-config
    - make
  host:
    - librsvg
    - libtiff
    - libjpeg-turbo
    - libjpeg-turbo
  run:
    - libjpeg-turbo
    - libtiff
    - libjpeg-turbo

test:
  commands:
    - ddjvu --help 2>&1 >/dev/null | grep Usage

about:
  home: http://djvu.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: Suite to create, manipulate and view DjVu ('déjà vu') documents

extra:
  recipe-maintainers:
    - izahn
