{% set name = "djvulibre" %}
{% set version = "3.5.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/djvu/DjVuLibre/{{ version }}/djvulibre-{{ version }}.tar.gz
  sha256: ee5e457d4cfebe566f94b99e5e3d3cc7f5c79ddb741c2ac2ba2e456f00329644

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - gnuconfig
    - librsvg  # needed for rsvg-convert, which must be executed on build host
    - libtool
    - make
    - pkg-config
  host:
    - libtiff
    - libjpeg-turbo

test:
  commands:
    - ddjvu --help 2>&1 >/dev/null | grep Usage

about:
  home: http://djvu.sourceforge.net/
  license: GPL-2.0-only
  license_file: COPYING
  summary: Suite to create, manipulate and view DjVu ('déjà vu') documents

extra:
  recipe-maintainers:
    - danielnachun
    - izahn
